[package]
name = "blink"
version = "0.1.0"
description = "A fast, private HTTP client for professional API work"
authors = ["Kyle Dougan"]
license = "MIT"
edition = "2021"

[lib]
name = "blink_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
reqwest = { version = "0.12", default-features = false, features = ["charset", "cookies", "http2", "json", "macos-system-configuration", "multipart", "rustls-tls", "rustls-tls-native-roots", "socks"] }
serde = { version = "1", features = ["derive"] }
cookie_store = { version = "0.22", features = ["serde_json"] }
reqwest_cookie_store = "0.9"
serde_json = "1"
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
tauri-plugin-window-state = "2.4.1"
tempfile = "3.27.0"
tokio = { version = "1", features = ["fs", "macros", "net", "sync"] }
tower-layer = "0.3"
tower-service = "0.3"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
