[package]
name = "blink"
description = "A fast, private HTTP client for professional API work"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1"
blink-core = { path = "../blink-core" }
futures = "0.3"
gpui-kit = { version = "0.7.0", features = [
    "tree-sitter",
    "tree-sitter-bash",
    "tree-sitter-go",
    "tree-sitter-graphql",
    "tree-sitter-javascript",
    "tree-sitter-python",
    "tree-sitter-rust",
] }
lsp-types = { version = "0.97.0", features = ["proposed"] }
serde_json = "1"
